version: "3"
services:
  aeternum-server-primary:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8081:8080
    networks:
      - api-network
  aeternum-server-secondary:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8082:8080
    networks:
      - api-network
  aeternum-load-balancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
