version: "3"
services:
  aeternum-api-1:
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    ports:
      - 8081:8080
    networks:
      - api-network
  aeternum-api-2:
    build:
      context: ../
      dockerfile: docker/server.Dockerfile
    ports:
      - 8082:8080
    networks:
      - api-network
  aeternum-load-balancer:
    build:
      context: ../
      dockerfile: docker/balancer.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
