name: Production Release

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.4"

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install Go modules
        run: |
          just tidy

      - name: Run tests
        run: |
          just test

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.4"

      - name: Install Github CLI
        run: |
          sudo apt-get install gh

      - name: Build release image
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
        run: |
          docker login ghcr.io -u jgfranco17 --password ${{ secrets.USER_GITHUB_TOKEN }}
          docker build -t aeternum:latest -f ./docker/server.Dockerfile .
          docker push ghcr.io/jgfranco17/aeternum:latest
